config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

kitchen/urls.py
from django.urls import path

from .views import (
    index,
    CookListView,
    CookDetailView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    remove_cook,
    assign_cook,
)


urlpatterns = [
    path("", index, name="index"),
    path("cook/", CookListView.as_view(), name="cook-list"),
    path("cook/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cook/create", CookCreateView.as_view(), name="cook-create"),
    path("cook/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
    path("cook/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
    path("dish/", DishListView.as_view(), name="dish-list"),
    path("dish/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dish/create", DishCreateView.as_view(), name="dish-create"),
    path("dish/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dish/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("dish/<int:pk>/remove/", remove_cook, name="remove-cook"),
    path("dish/<int:pk>/assign/", assign_cook, name="assign-cook"),
    path("dish-type/", DishTypeListView.as_view(), name="dish-type-list"),
    path("dish-type/create", DishTypeCreateView.as_view(), name="dish-type-create"),
    path("dish-type/<int:pk>/update/", DishTypeUpdateView.as_view(), name="dish-type-update"),
    path("dish-type/<int:pk>/delete/", DishTypeDeleteView.as_view(), name="dish-type-delete"),
]

app_name = "kitchen"

py_resto_management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

templates/includes/footer.html
<!--  <footer class="footer pt-5 mt-5">-->
<!--    <hr class="horizontal dark mb-5">-->
<!--    <div class="container">-->
<!--      <div class=" row">-->
<!--        <div class="col-md-3 mb-4 ms-auto">-->
<!--          <div>-->
<!--            <h6 class="text-gradient text-primary font-weight-bolder">Soft UI Design System</h6>-->
<!--          </div>-->
<!--          <div>-->
<!--            <h6 class="mt-3 mb-2 opacity-8">Social</h6>-->
<!--            <ul class="d-flex flex-row ms-n3 nav">-->
<!--              <li class="nav-item">-->
<!--                <a class="nav-link pe-1" href="https://www.facebook.com/CreativeTim/" target="_blank">-->
<!--                  <i class="fab fa-facebook text-lg opacity-8"></i>-->
<!--                </a>-->
<!--              </li>-->
<!--              <li class="nav-item">-->
<!--                <a class="nav-link pe-1" href="https://twitter.com/creativetim" target="_blank">-->
<!--                  <i class="fab fa-twitter text-lg opacity-8"></i>-->
<!--                </a>-->
<!--              </li>-->
<!--              <li class="nav-item">-->
<!--                <a class="nav-link pe-1" href="https://dribbble.com/creativetim" target="_blank">-->
<!--                  <i class="fab fa-dribbble text-lg opacity-8"></i>-->
<!--                </a>-->
<!--              </li>-->
<!--              <li class="nav-item">-->
<!--                <a class="nav-link pe-1" href="https://github.com/creativetimofficial" target="_blank">-->
<!--                  <i class="fab fa-github text-lg opacity-8"></i>-->
<!--                </a>-->
<!--              </li>-->
<!--              <li class="nav-item">-->
<!--                <a class="nav-link pe-1" href="https://www.youtube.com/channel/UCVyTG4sCw-rOvB9oHkzZD1w" target="_blank">-->
<!--                  <i class="fab fa-youtube text-lg opacity-8"></i>-->
<!--                </a>-->
<!--              </li>-->
<!--            </ul>-->
<!--          </div>-->
<!--        </div>-->
<!--        <div class="col-md-2 col-sm-6 col-6 mb-4">-->
<!--          <div>-->
<!--            <h6 class="text-gradient text-primary text-sm">Company</h6>-->
<!--            <ul class="flex-column ms-n3 nav">-->
<!--              <li class="nav-item">-->
<!--                <a class="nav-link" href="https://www.creative-tim.com/presentation" target="_blank">-->
<!--                  About Us-->
<!--                </a>-->
<!--              </li>-->
<!--              <li class="nav-item">-->
<!--                <a class="nav-link" href="https://www.creative-tim.com/templates/free" target="_blank">-->
<!--                  Freebies-->
<!--                </a>-->
<!--              </li>-->
<!--              <li class="nav-item">-->
<!--                <a class="nav-link" href="https://www.creative-tim.com/templates/premium" target="_blank">-->
<!--                  Premium Tools-->
<!--                </a>-->
<!--              </li>-->
<!--              <li class="nav-item">-->
<!--                <a class="nav-link" href="https://www.creative-tim.com/blog" target="_blank">-->
<!--                  Blog-->
<!--                </a>-->
<!--              </li>-->
<!--            </ul>-->
<!--          </div>-->
<!--        </div>-->
<!--        <div class="col-md-2 col-sm-6 col-6 mb-4">-->
<!--          <div>-->
<!--            <h6 class="text-gradient text-primary text-sm">Resources</h6>-->
<!--            <ul class="flex-column ms-n3 nav">-->
<!--              <li class="nav-item">-->
<!--                <a class="nav-link" href="https://iradesign.io/" target="_blank">-->
<!--                  Illustrations-->
<!--                </a>-->
<!--              </li>-->
<!--              <li class="nav-item">-->
<!--                <a class="nav-link" href="https://www.creative-tim.com/bits" target="_blank">-->
<!--                  Bits & Snippets-->
<!--                </a>-->
<!--              </li>-->
<!--              <li class="nav-item">-->
<!--                <a class="nav-link" href="https://www.creative-tim.com/affiliates/new" target="_blank">-->
<!--                  Affiliate Program-->
<!--                </a>-->
<!--              </li>-->
<!--            </ul>-->
<!--          </div>-->
<!--        </div>-->
<!--        <div class="col-md-2 col-sm-6 col-6 mb-4">-->
<!--          <div>-->
<!--            <h6 class="text-gradient text-primary text-sm">Help & Support</h6>-->
<!--            <ul class="flex-column ms-n3 nav">-->
<!--              <li class="nav-item">-->
<!--                <a class="nav-link" href="https://www.creative-tim.com/contact-us" target="_blank">-->
<!--                  Contact Us-->
<!--                </a>-->
<!--              </li>-->
<!--              <li class="nav-item">-->
<!--                <a class="nav-link" href="https://www.creative-tim.com/knowledge-center" target="_blank">-->
<!--                  Knowledge Center-->
<!--                </a>-->
<!--              </li>-->
<!--              <li class="nav-item">-->
<!--                <a class="nav-link" href="https://services.creative-tim.com/?ref=ct-soft-ui-footer" target="_blank">-->
<!--                  Custom Development-->
<!--                </a>-->
<!--              </li>-->
<!--              <li class="nav-item">-->
<!--                <a class="nav-link" href="https://www.creative-tim.com/sponsorships" target="_blank">-->
<!--                  Sponsorships-->
<!--                </a>-->
<!--              </li>-->
<!--            </ul>-->
<!--          </div>-->
<!--        </div>-->
<!--        <div class="col-md-2 col-sm-6 col-6 mb-4 me-auto">-->
<!--          <div>-->
<!--            <h6 class="text-gradient text-primary text-sm">Legal</h6>-->
<!--            <ul class="flex-column ms-n3 nav">-->
<!--              <li class="nav-item">-->
<!--                <a class="nav-link" href="https://www.creative-tim.com/terms" target="_blank">-->
<!--                  Terms & Conditions-->
<!--                </a>-->
<!--              </li>-->
<!--              <li class="nav-item">-->
<!--                <a class="nav-link" href="https://www.creative-tim.com/privacy" target="_blank">-->
<!--                  Privacy Policy-->
<!--                </a>-->
<!--              </li>-->
<!--              <li class="nav-item">-->
<!--                <a class="nav-link" href="https://www.creative-tim.com/license" target="_blank">-->
<!--                  Licenses (EULA)-->
<!--                </a>-->
<!--              </li>-->
<!--            </ul>-->
<!--          </div>-->
<!--        </div>-->
<!--        <div class="col-12">-->
<!--          <div class="text-center">-->
<!--            <p class="my-4 text-sm">-->
<!--              Soft UI Design System by &copy; <a target="_blank" href="https://bit.ly/3fKQZaL" target="_blank">Creative Tim</a> -->
<!--              - Coded by <a target="_blank" href="https://appseed.us" target="_blank">AppSeed</a>.-->
<!--            </p>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
<!--  </footer>-->

templates/includes/navigation.html
 <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid">
            <a class="navbar-brand font-weight-bolder ms-sm-3"
               href="/" rel="tooltip" title="Home page" data-placement="bottom">
              Restaurant Management System
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center"
                     id="dropdownMenuPages"
                     data-bs-toggle="dropdown" aria-expanded="false">
                    Cooks
                    <img src="/static/assets/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-1">
                  </a>

                  <div class="dropdown-menu dropdown-menu-animation dropdown-md p-3 border-radius-lg mt-0 mt-lg-3"
                       aria-labelledby="dropdownMenuPages">

                    <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-center align-items-center px-0 mt-2">
                      <div class="d-inline-block">
                        <div class="icon icon-shape icon-xs border-radius-md bg-gradient-primary text-center me-2
                                    d-flex align-items-center justify-content-center ps-0">
                          <svg width="12px" height="12px" viewBox="0 0 42 42"
                               xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                            <title>Info about cooks at the kitchen</title>
                            <g fill="none" fill-rule="evenodd">
                              <g fill="#FFFFFF" fill-rule="nonzero">
                                <path d="M12.25,17.5 L8.75,17.5 L8.75,1.75 C8.75,0.78225 9.53225,0 10.5,0
                                         L31.5,0 C32.46775,0 33.25,0.78225 33.25,1.75 L33.25,12.25
                                         L29.75,12.25 L29.75,3.5 L12.25,3.5 L12.25,17.5 Z" opacity="0.6"></path>
                                <path d="M40.25,14 L24.5,14 C23.53225,14 22.75,14.78225 22.75,15.75
                                         L22.75,38.5 L19.25,38.5 L19.25,22.75 C19.25,21.78225 18.46775,21
                                         17.5,21 L1.75,21 C0.78225,21 0,21.78225 0,22.75 L0,40.25
                                         C0,41.21775 0.78225,42 1.75,42 L40.25,42 C41.21775,42
                                         42,41.21775 42,40.25 L42,15.75 C42,14.78225 41.21775,14
                                         40.25,14 Z M12.25,36.75 L7,36.75 L7,33.25 L12.25,33.25
                                         L12.25,36.75 Z M12.25,29.75 L7,29.75 L7,26.25 L12.25,26.25
                                         L12.25,29.75 Z M35,36.75 L29.75,36.75 L29.75,33.25 L35,33.25
                                         L35,36.75 Z M35,29.75 L29.75,29.75 L29.75,26.25 L35,26.25
                                         L35,29.75 Z M35,22.75 L29.75,22.75 L29.75,19.25 L35,19.25
                                         L35,22.75 Z"></path>
                              </g>
                            </g>
                          </svg>
                        </div>
                      </div>
                      Cooks
                    </h6>
                    <a href="{% url 'kitchen:cook-list' %}" class="dropdown-item border-radius-md">
                      Cook List
                    </a>
                  </div>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
                    Dishes
                    <img src="/static/assets/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-1">
                  </a>
                  <div class="dropdown-menu dropdown-menu-animation dropdown-md p-3 border-radius-lg mt-0 mt-lg-3" aria-labelledby="dropdownMenuPages">
                    <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-center align-items-center px-0 mt-2">
                      <div class="d-inline-block">
                        <div class="icon icon-shape icon-xs border-radius-md bg-gradient-primary text-center me-2 d-flex align-items-center justify-content-center ps-0">
                          <svg width="12px" height="12px" viewBox="0 0 42 42" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                            <title>Info about dishes</title>
                            <g id="Basic-Elements" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                              <g id="Rounded-Icons" transform="translate(-1869.000000, -293.000000)" fill="#FFFFFF" fill-rule="nonzero">
                                <g id="Icons-with-opacity" transform="translate(1716.000000, 291.000000)">
                                  <g id="office" transform="translate(153.000000, 2.000000)">
                                    <path d="M12.25,17.5 L8.75,17.5 L8.75,1.75 C8.75,0.78225 9.53225,0 10.5,0 L31.5,0 C32.46775,0 33.25,0.78225 33.25,1.75 L33.25,12.25 L29.75,12.25 L29.75,3.5 L12.25,3.5 L12.25,17.5 Z" id="Path" opacity="0.6"></path>
                                    <path d="M40.25,14 L24.5,14 C23.53225,14 22.75,14.78225 22.75,15.75 L22.75,38.5 L19.25,38.5 L19.25,22.75 C19.25,21.78225 18.46775,21 17.5,21 L1.75,21 C0.78225,21 0,21.78225 0,22.75 L0,40.25 C0,41.21775 0.78225,42 1.75,42 L40.25,42 C41.21775,42 42,41.21775 42,40.25 L42,15.75 C42,14.78225 41.21775,14 40.25,14 Z M12.25,36.75 L7,36.75 L7,33.25 L12.25,33.25 L12.25,36.75 Z M12.25,29.75 L7,29.75 L7,26.25 L12.25,26.25 L12.25,29.75 Z M35,36.75 L29.75,36.75 L29.75,33.25 L35,33.25 L35,36.75 Z M35,29.75 L29.75,29.75 L29.75,26.25 L35,26.25 L35,29.75 Z M35,22.75 L29.75,22.75 L29.75,19.25 L35,19.25 L35,22.75 Z" id="Shape"></path>
                                  </g>
                                </g>
                              </g>
                            </g>
                          </svg>
                        </div>
                      </div>
                      Dishes
                    </h6>
                    <a href="{% url 'kitchen:dish-list' %}" class="dropdown-item border-radius-md">
                      Dish List
                    </a>
                  </div>
                </li>
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
                    Dish Types
                    <img src="/static/assets/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-1">
                  </a>
                  <div class="dropdown-menu dropdown-menu-animation dropdown-md p-3 border-radius-lg mt-0 mt-lg-3"
                       aria-labelledby="dropdownMenuPages">

                    <h6 class="dropdown-header text-dark font-weight-bolder d-flex justify-content-center align-items-center px-0 mt-2">
                      <div class="d-inline-block">
                        <div class="icon icon-shape icon-xs border-radius-md bg-gradient-primary text-center me-2
                                    d-flex align-items-center justify-content-center ps-0">
                          <svg width="12px" height="12px" viewBox="0 0 42 42"
                               xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                            <title>Info about the dish types</title>
                            <g fill="none" fill-rule="evenodd">
                              <g fill="#FFFFFF" fill-rule="nonzero">
                                <path d="M12.25,17.5 L8.75,17.5 L8.75,1.75 C8.75,0.78225 9.53225,0 10.5,0
                                         L31.5,0 C32.46775,0 33.25,0.78225 33.25,1.75 L33.25,12.25
                                         L29.75,12.25 L29.75,3.5 L12.25,3.5 L12.25,17.5 Z" opacity="0.6"></path>
                                <path d="M40.25,14 L24.5,14 C23.53225,14 22.75,14.78225 22.75,15.75
                                         L22.75,38.5 L19.25,38.5 L19.25,22.75 C19.25,21.78225 18.46775,21
                                         17.5,21 L1.75,21 C0.78225,21 0,21.78225 0,22.75 L0,40.25
                                         C0,41.21775 0.78225,42 1.75,42 L40.25,42 C41.21775,42
                                         42,41.21775 42,40.25 L42,15.75 C42,14.78225 41.21775,14
                                         40.25,14 Z M12.25,36.75 L7,36.75 L7,33.25 L12.25,33.25
                                         L12.25,36.75 Z M12.25,29.75 L7,29.75 L7,26.25 L12.25,26.25
                                         L12.25,29.75 Z M35,36.75 L29.75,36.75 L29.75,33.25 L35,33.25
                                         L35,36.75 Z M35,29.75 L29.75,29.75 L29.75,26.25 L35,26.25
                                         L35,29.75 Z M35,22.75 L29.75,22.75 L29.75,19.25 L35,19.25
                                         L35,22.75 Z"></path>
                              </g>
                            </g>
                          </svg>
                        </div>
                      </div>
                      Dish Types
                    </h6>
                      <a href="{% url 'kitchen:dish-type-list' %}" class="dropdown-item border-radius-md">
                        Dish Types List
                      </a>
                  </div>

                {% if user.is_authenticated %}
                  <li class="nav-item ms-lg-auto">
                    <a class="nav-link nav-link-icon me-2" href="{{ user.get_absolute_url }}">
                      <i class="fa fa-sign-out me-1"></i>
                      <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="User">{{ user.get_username }}</p>
                    </a>
                  </li>
                  <li class="nav-item my-auto ms-3 ms-lg-0">
                    <form method="post" action="{% url 'logout' %}">
                      {% csrf_token %}
                      <button type="submit"
                              class="btn btn-sm bg-gradient-primary btn-round mb-0 me-1 mt-2 mt-md-0">
                        Logout
                      </button>
                    </form>
                  </li>

                {% else %}
                 <li class="nav-item my-auto ms-3 ms-lg-0">
                    <a href="{% url 'login' %}"
                       target="_blank"
                       class="btn btn-sm  bg-gradient-primary btn-round mb-0 me-1 mt-2 mt-md-0">Login</a>
                  </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/scripts.html
  <script src="/static/assets/js/core/popper.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="/static/assets/js/plugins/prism.min.js"></script>
  <script src="/static/assets/js/plugins/parallax.min.js"></script>