config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

kitchen/urls.py
from django.urls import path

from .views import (
    index,
    CookListView,
    CookDetailView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    remove_cook,
    assign_cook,
)


urlpatterns = [
    path("", index, name="index"),
    path("cook/", CookListView.as_view(), name="cook-list"),
    path("cook/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cook/create", CookCreateView.as_view(), name="cook-create"),
    path("cook/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
    path("cook/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
    path("dish/", DishListView.as_view(), name="dish-list"),
    path("dish/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dish/create", DishCreateView.as_view(), name="dish-create"),
    path("dish/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dish/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("dish/<int:pk>/remove/", remove_cook, name="remove-cook"),
    path("dish/<int:pk>/assign/", assign_cook, name="assign-cook"),
    path("dish-type/", DishTypeListView.as_view(), name="dish-type-list"),
    path("dish-type/create", DishTypeCreateView.as_view(), name="dish-type-create"),
    path("dish-type/<int:pk>/update/", DishTypeUpdateView.as_view(), name="dish-type-update"),
    path("dish-type/<int:pk>/delete/", DishTypeDeleteView.as_view(), name="dish-type-delete"),
]

app_name = "kitchen"

py_resto_management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

kitchen/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import ForeignKey
from django.urls import reverse

from kitchen.validators import validate_years_of_experience


class Cook(AbstractUser):
    years_of_experience = models.PositiveIntegerField(
        default=0,
        validators=[validate_years_of_experience],
        null=False,
        blank=False
    )

    def get_absolute_url(self):
        return reverse("kitchen:cook-detail", args=[str(self.id)])


    def __str__(self):
        return f"{self.username}: ({self.years_of_experience} years of experience)"


class DishType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    dish_type = ForeignKey(DishType, on_delete=models.CASCADE, related_name="dishes")
    cooks = models.ManyToManyField(Cook, related_name="dishes")

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "dishes"
        verbose_name = "dish"

    def get_absolute_url(self):
        return reverse("kitchen:dish-detail", args=[str(self.id)])

    def __str__(self):
        return f"{self.name}, dish_type: {self.dish_type}, price: {self.price}"

kitchen/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from kitchen.models import Cook, Dish
from kitchen.validators import validate_years_of_experience


class CookCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ("email", "first_name", "last_name", "years_of_experience")

    def years_of_experience(self):
        return validate_years_of_experience(self.cleaned_data["years_of_experience"])


class CookUpdateForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = ["years_of_experience"]
        widgets = {
            "years_of_experience": forms.NumberInput(attrs={"class": "form-control", "min": 0, "max": 100}),
        }


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Dish
        fields = ["name", "description", "price", "dish_type", "cooks"]


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name"
            }
        ),
    )


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name"
            }
        ),
    )


class CookSearchForm(forms.Form):
    last_name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by Last Name"
            }
        ),
    )

kitchen/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from kitchen.forms import DishSearchForm, CookSearchForm, CookCreationForm, CookUpdateForm, DishForm, DishTypeSearchForm
from kitchen.models import Cook, DishType, Dish

@login_required(login_url="login")
def index(request: HttpRequest):
    num_cooks = Cook.objects.count()
    num_dish_types = DishType.objects.count()
    num_dishes = Dish.objects.count()
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1
    context = {
        "num_cooks": num_cooks,
        "num_dish_types": num_dish_types,
        "num_dishes": num_dishes,
        "num_visits": num_visits + 1,
    }
    return render(request, "kitchen/index.html", context=context)


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    queryset = Cook.objects.all().order_by("last_name")
    paginate_by = 5

    def get_context_data(
        self, *, object_list=..., **kwargs
    ):
        context = super(CookListView, self).get_context_data(**kwargs)
        last_name = self.request.GET.get("last_name", "")
        context["last_name"] = last_name
        context["search_form"] = CookSearchForm(
            initial={"last_name": last_name}
        )
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        form = CookSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(last_name__icontains=form.cleaned_data["last_name"])
        return queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookUpdateForm
    success_url = reverse_lazy("kitchen:cook-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("kitchen:cook-list")


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    queryset = Dish.objects.all().order_by("name")
    paginate_by = 5
    context_object_name = "dish_list"

    def get_context_data(
        self, *, object_list=..., **kwargs
    ):
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["name"] = name
        context["search_form"] = DishSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = super().get_queryset().select_related("dish_type")
        form = DishSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset

class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dish-list")


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    queryset = DishType.objects.all().order_by("name")
    paginate_by = 5
    template_name = "kitchen/dish_type_list.html"
    context_object_name = "dish_type_list"

    def get_context_data(
        self, *, object_list=..., **kwargs
    ):
        context = super(DishTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["name"] = name
        context["search_form"] = DishTypeSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        form = DishTypeSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset

class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-type-list")
    template_name = "kitchen/dish_type_form.html"
    context_object_name = "dish_type"


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    success_url = reverse_lazy("kitchen:dish-type-list")
    template_name = "kitchen/dish_type_confirm_delete.html"
    context_object_name = "dish_type"


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("kitchen:dish-type-list")
    template_name = "kitchen/dish_type_form.html"
    context_object_name = "dish_type"


@login_required
def assign_cook(request, pk):
    dish = get_object_or_404(Dish, pk=pk)
    dish.cooks.add(request.user)
    return redirect("kitchen:dish-detail", pk=pk)

@login_required
def remove_cook(request, pk):
    dish = get_object_or_404(Dish, pk=pk)
    dish.cooks.remove(request.user)
    return redirect("kitchen:dish-detail", pk=pk)

templates/kitchen/cook_confirm_delete.html
{% extends 'layouts/base-presentation.html' %}

{% block title %} Cooks {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block page_title %}Cooks{% endblock page_title %}

{% block content %}
  <h1>Delete Cook</h1>

  <p>Are you sure you want to delete the dish: {{ cook }}</p>
  <form action="" method="post">
    {% csrf_token %}
      <input type="submit" value="Yes, delete" class="btn btn-danger">
      <a href="{% url 'kitchen:cook-detail' pk=cook.id %}" class="btn btn-primary">Cancel</a>
  </form>

{% endblock %}

templates/kitchen/cook_detail.html
{% extends 'layouts/base-presentation.html' %}

{% load crispy_forms_filters %}

{% block title %} Cooks {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block page_title %}Cooks{% endblock page_title %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center">
    <h1 class="mb-0">Cook detail info:</h1>
    <div>
      <a href="{% url 'kitchen:cook-delete' pk=cook.id %}" class="btn btn-danger link-to-page me-2">
        Delete
      </a>
      <a href="{% url 'kitchen:cook-update' pk=cook.id %}" class="btn btn-primary link-to-page">
        Update
      </a>
    </div>
  </div>

  <br>
  <p><strong>Cook ID:</strong>    {{ cook.id }}</p>
  <p><strong>Cook Username:</strong>     {{ cook.username}}</p>
  <p><strong>Cook Last Name:</strong>     {{ cook.first_name }}</p>
  <p><strong>Cook First Name:</strong>     {{ cook.last_name }}</p>
  <p><strong>Years of experience:</strong>     {{ cook.years_of_experience }}</p>
    <h4>Cook Dishes:</h4>
    <ul>
    {% for dish in cook.dishes.all %}
      <li>{{ dish.name }} {{ dish.dish_type.name }} - {{ dish.price }}</li>
    {% endfor %}
    </ul>
{% endblock %}

templates/kitchen/cook_form.html
{% extends 'layouts/base-presentation.html' %}

{% load crispy_forms_filters %}

{% block title %} Cooks {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block page_title %}Cooks{% endblock page_title %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} cook</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/cook_list.html
{% extends 'layouts/base-presentation.html' %}

{% load crispy_forms_filters %}

{% block title %} Cooks {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block page_title %}Cooks{% endblock page_title %}

{% block content %}
  <div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h1 class="mb-0">Cook List</h1>
      <a href="{% url 'kitchen:cook-create' %}" class="btn btn-primary link-to-page">
        Create
      </a>
    </div>
    <form method="get" action="" class="form-inline">
      {{ search_form|crispy }}
      <input class="btn btn-secondary" type="submit" value="🔍">
    </form>

    {% if cook_list %}
      <table>
        <tr>
          <th>Cook ID</th>
          <th>Username</th>
          <th>Last Name</th>
          <th>First Name</th>
          <th>Experience</th>
        </tr>
        {% for cook in cook_list %}
          <tr>
            <td><a href="{{ cook.get_absolute_url }}">{{ cook.id }}</a></td>
            <td>
              {{ cook.username }}{% if cook == user %} (Me){% endif %}
            </td>
            <td>{{ cook.last_name }}</td>
            <td>{{ cook.first_name }}</td>
            <td>{{ cook.years_of_experience }}</td>
          </tr>
        {% endfor %}
      </table>
    {% endif %}
  </div>
{% endblock %}

templates/kitchen/dish_confirm_delete.html
{% extends 'layouts/base-presentation.html' %}

{% block title %} Dishes {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block page_title %}Dishes{% endblock page_title %}

{% block content %}
  <h1>Delete Dish</h1>

  <p>Are you sure you want to delete the dish: {{ dish }}</p>
  <form action="" method="post">
    {% csrf_token %}
      <input type="submit" value="Yes, delete" class="btn btn-danger">
      <a href="{% url 'kitchen:dish-detail' pk=dish.id %}" class="btn btn-primary">Cancel</a>
  </form>

{% endblock %}

templates/kitchen/dish_detail.html
{% extends 'layouts/base-presentation.html' %}

{% block title %} Dishes {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block page_title %}Dishes{% endblock page_title %}

{% block content %}
  <div class="d-flex justify-content-start gap-2 mb-4">
    <a href="{% url 'kitchen:dish-update' pk=dish.id %}" class="btn btn-primary float-start mr-1">Update the dish</a>
    <a href="{% url 'kitchen:dish-delete' pk=dish.id %}" class="btn btn-danger mr-1">Delete the dish</a>
  </div>
  <h1>Dish Detail Info</h1>
  <p><strong>Dish ID:</strong>    {{ dish.id }}</p>
  <p><strong>Dish Name:</strong>     {{ dish.name}}</p>
  <p><strong>Dish Type:</strong>     {{ dish.dish_type.name }}</p>
  <p><strong>Dish Description:</strong>     {{ dish.description }}</p>
  <p><strong>Dish Price:</strong>     {{ dish.price }}</p>
  <p><strong>Cook:</strong>
    {% for cook in dish.cooks.all %}
      {{ cook.username }}{% if not forloop.last %}, {% endif %}
    {% empty %}
      No cooks
    {% endfor %}
  </p>
  {% if user in dish.cooks.all %}
      <form method="post" action="{% url 'kitchen:remove-cook' pk=dish.id %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Delete me from this dish</button>
      </form>
  {% else %}
      <form method="post" action="{% url 'kitchen:assign-cook' pk=dish.id %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-success">Assign me to this car</button>
      </form>
  {% endif %}
{% endblock %}

templates/kitchen/dish_form.html
{% extends 'layouts/base-presentation.html' %}

{% load crispy_forms_filters %}

{% block title %} Dishes {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block page_title %}Dishes{% endblock page_title %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/dish_list.html
{% extends 'layouts/base-presentation.html' %}

{% load crispy_forms_filters %}

{% block title %} Dishes {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block page_title %}Dishes{% endblock page_title %}

{% block content %}
  <h1>
    Dish List
    <a href="{% url 'kitchen:dish-create' %}" class="btn btn-primary link-to-page">
    Create
    </a>
  </h1>
  <form method="get" action="" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-secondary" type="submit" value="🔍">
  </form>
  <br>
  {% if dish_list %}
    <table>
      <tr>
        <th>Dish ID</th>
        <th>Dish Name</th>
        <th>Dish Type</th>
        <th>Dish Description</th>
        <th>Price</th>
        <th>Cook</th>
      </tr>
      {% for dish in dish_list %}
        <tr>
          <td><a href="{{ dish.get_absolute_url }}">{{ dish.id }}</a></td>
          <td>{{ dish.name }}</td>
          <td>{{ dish.dish_type.name }}</td>
          <td>{{ dish.description }}</td>
          <td>{{ dish.price }}</td>
          <td>
            {% for cook in dish.cooks.all %}
              {{ cook.username }}{% if not forloop.last %}, {% endif %}
            {% empty %}
              No cooks
            {% endfor %}
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>No dishes available.</p>
  {% endif %}
{% endblock %}

templates/kitchen/dish_type_confirm_delete.html
{% extends 'layouts/base-presentation.html' %}

{% block title %} Dish Types {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block page_title %}Dish Types{% endblock page_title %}

{% block content %}
  <h1>Delete Dish Type</h1>

  <p>Are you sure you want to delete the dish type: {{ dish_type }}</p>
  <form action="" method="post">
    {% csrf_token %}
      <input type="submit" value="Yes, delete" class="btn btn-danger">
      <a href="{% url 'kitchen:dish-type-list' %}" class="btn btn-primary">Cancel</a>
  </form>

{% endblock %}

templates/kitchen/dish_type_form.html
{% extends 'layouts/base-presentation.html' %}

{% load crispy_forms_filters %}

{% block title %} Dish Types {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block page_title %}Dish Types{% endblock page_title %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish type</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/dish_type_list.html
{% extends 'layouts/base-presentation.html' %}

{% load crispy_forms_filters %}

{% block title %} Dish Types {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block page_title %}Dish Types{% endblock page_title %}

{% block content %}
  <h1>
    Dish Types List
    <a href="{% url 'kitchen:dish-type-create' %}" class="btn btn-primary link-to-page">
       Create
    </a>
  </h1>
    <form method="get" action="" class="form-inline">
      {{ search_form|crispy }}
      <input class="btn btn-secondary" type="submit" value="🔍">
    </form>
  {% if dish_type_list %}
    <table class="table">
      <tr>
        <td>ID</td>
        <td>Name</td>
        <td>Update</td>
        <td>Delete</td>
      </tr>
      {% for dish_type in dish_type_list %}
        <tr>
          <th>{{ dish_type.id }}</th>
          <th>{{ dish_type.name}}</th>
          <th><a href="{% url 'kitchen:dish-type-update' pk=dish_type.id%}">UPDATE</a></th>
          <th><a href="{% url 'kitchen:dish-type-delete' pk=dish_type.id%}">DELETE</a></th>
        </tr>
      {% endfor %}
    </table>
      {% else %}
    <p>There are no dish types in Restaurant</p>
  {% endif %}
{% endblock %}

templates/kitchen/index.html
{% extends 'layouts/base-presentation.html' %}

{% block title %} Home page {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block page_title %}Home Page{% endblock page_title %}

{% block content %}{% endblock content %}

  <section class="pt-3 pb-4 mt-5" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
          <div class="row">
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"><span id="state1" countTo="{{ num_dish_types }}">0</span>+</h1>
                <h5 class="mt-3">Dish types</h5>
                <p class="text-sm">...</p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"> <span id="state2" countTo="{{ num_dishes }}">0</span>+</h1>
                <h5 class="mt-3">Dishes</h5>
                <p class="text-sm">...</p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary" id="state3" countTo="{{ num_cooks }}">0</h1>
                <h5 class="mt-3">Cooks</h5>
                <p class="text-sm">...</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>



<!-- Specific JS goes HERE -->
{% block javascripts %}

  <script src="/static/assets/js/plugins/countup.min.js"></script>
  <script src="/static/assets/js/plugins/choices.min.js"></script>
  <script src="/static/assets/js/plugins/rellax.min.js"></script>
  <script src="/static/assets/js/plugins/tilt.min.js"></script>
  <script src="/static/assets/js/plugins/choices.min.js"></script>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="/static/assets/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>
  <script type="text/javascript">
    if (document.getElementById('state1')) {
      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
      if (!countUp.error) {
        countUp.start();
      } else {
        console.error(countUp.error);
      }
    }
    if (document.getElementById('state2')) {
      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
      if (!countUp1.error) {
        countUp1.start();
      } else {
        console.error(countUp1.error);
      }
    }
    if (document.getElementById('state3')) {
      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
      if (!countUp2.error) {
        countUp2.start();
      } else {
        console.error(countUp2.error);
      };
    }
  </script>

{% endblock javascripts %}